# Generated by Django 4.1.2 on 2022-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_created_add_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('rejected', 'Откланенная')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
